Link phages and host by finding potenial share attachment sites in host tRNAs.

#+BEGIN_SRC sh
# get it
git clone https://github.com/thackl/host-phage-tRNA-att-finder

# run it
cd host-phage-tRNA-att-finder
bin/host-phage-tRNA-att-finder host-contigs.fa phage-contigs.fa

# test it on sample data (Prochlorococcus MED4 (host) and 2 cyanophages
# with integrase gene and putative attachment site to tRNA-Leu(taa)
bin/host-phage-tRNA-att-finder -o test-run data/MED4.fna data/P-SSP7-like.fna
#+END_SRC

*Requires*
- blastn/makeblastdb, samtools, seqkit, aragorn
- sed,sort

** Output
Blast table with potential attachment sites. Here it shows that both phages have a 40bp exact match to the tRNA-Leu(taa) of MED4:

#+BEGIN_ASCII
MED4_00626__tRNA-Leu(taa)       AY939843        100.000 40      0       0       1       40      5859    5898    5.06e-12        59.7
MED4_01491__tRNA-Leu(caa)       AY939843        87.179  39      5       0       1       39      5860    5898    2.50e-07        44.0
MED4_00064__tRNA-Leu(aag)       AY939843        100.000 22      0       0       8       29      5866    5887    2.56e-04        34.0
MED4_00245__tRNA-Leu(tag)       AY939843        100.000 22      0       0       7       28      5866    5887    2.51e-04        34.0
MED4_01810__tRNA-Arg(ccg)       AY939843        100.000 16      0       0       52      67      2583    2598    0.079   25.4
MED4_00626__tRNA-Leu(taa)       GU071093        100.000 40      0       0       1       40      4984    5023    5.06e-12        59.7
MED4_01491__tRNA-Leu(caa)       GU071093        87.179  39      5       0       1       39      4985    5023    2.50e-07        44.0
MED4_00064__tRNA-Leu(aag)       GU071093        100.000 22      0       0       8       29      4991    5012    2.56e-04        34.0
MED4_00245__tRNA-Leu(tag)       GU071093        100.000 22      0       0       7       28      4991    5012    2.51e-04        34.0
MED4_01810__tRNA-Arg(ccg)       GU071093        100.000 16      0       0       52      67      1651    1666    0.079   25.4
#+END_ASCII

** Description

1. Host tRNAs are predicted in the host contigs using aragorn, and extracted
2. The host tRNAs are blasted against the phage contigs looking for
   high-identity short matches: >80% idy, ~20-40bp. A modified blast match/gap
   cost model for blast is used to enforce these kind of hits.
=-task blastn -reward 1 -penalty -1 -gapopen 2 -gapextend 1 -perc_identity 80 -evalue 10e-2=
